name: CI

on:
  push:
    branches:
      - master
      - release/*
    
jobs:
  lint:
    name: Run phpstan checker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga
      with:
        args: analyse src/ --level 7

